const adBlock = () => {
  const removeElements = (selector) => {
    document.querySelectorAll(selector).forEach((el) => el.remove());
  };

  // 広告を削除するセレクターを指定して、removeElements関数を呼び出す
  removeElements(
    "img[src='https://yt3.ggpht.com/ytc/APkrFKa2X9oS3Z08OTPavY2Xapfg-iBjCoNF4G2XD2JV8w=s48-c-k-c0x00ffffff-no-rj']"
  );
  removeElements("img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault.jpg']");
  removeElements("img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault.jpg']");
  removeElements("img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default.jpg']");
  removeElements("img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault.jpg']");
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault.jpg']"
  );
  removeElements("img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720.jpg']");
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/maxresdefault_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hq720_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/hqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/mqdefault_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/default_live_webp.jpg']"
  );
  removeElements(
    "img[src='https://i.ytimg.com/vi/5SUVOIelSBA/sddefault_live_webp.jpg']"
  );
  blockElements(`iframe[src*="pagead2.googlesyndication.com"]`);
  blockElements(`img[src*="pagead2.googlesyndication.com"]`);
};
const onPageLoad = () => {
  adBlock();
  setTimeout(adBlock, 3000);
  setTimeout(adBlock, 5000);
};

document.addEventListener("DOMContentLoaded", onPageLoad);
window.addEventListener("load", onPageLoad);
chrome.runtime.onMessage.addListener(adBlock);
